services:
  timezone.factory.extract:
    class: Vainyl\Time\Factory\ExtractTimeZoneFactory
    tags:
      - {name: timezone.factory, priority: 100}
  timezone.factory.full:
    class: Vainyl\Time\Factory\FullNameTimeZoneFactory
    tags:
      - {name: timezone.factory, priority: 200}
  timezone.factory.default:
    class: Vainyl\Time\Factory\DefaultTimeZoneFactory
    arguments: ['UTC']
    tags:
      - {name: timezone.factory, priority: 300}
  timezone.factory.chain:
    class: Vainyl\Time\Chain\TimeZoneFactoryChain
  timezone.factory: '@timezone.factory.chain'
  time.factory:
    class: Vainyl\Time\Factory\TimeFactory
    arguments: ['@locale.storage', '@timezone.factory']
  time.provider:
    class: Vainyl\Time\Provider\TimeProvider
    arguments: ['@time.factory']